services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "${DBPORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/db_creacion.sql:/docker-entrypoint-initdb.d/db_creacion.sql

  spark:
    image: bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    volumes:
      - ./carga:/carga
      - ./extraccion:/extraccion

  airflow:
    build: ./airflow
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${USER}:${PASSWORD}@postgres:5432/${DBNAME}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./carga:/carga
      - ./extraccion:/extraccion
      - ./scripts:/scripts
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  superset:
    image: apache/superset:latest
    ports:
      - "8082:8088"  # Superset usa el puerto 8088 por defecto
    environment:
      - SUPERSET_SECRET_KEY=superset_secret_key
      - SUPERSET_LOAD_EXAMPLES=no
    volumes:
      - superset_data:/app/superset_home
    depends_on:
      - postgres
      
volumes:
  postgres_data:
  superset_data: